In [19]:
import numpy as np

In [140]:
lst = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
lst[0:2, 1:4]   #array([[2, 3, 4],
                     # [7, 8, 9]])            #------------------------------(rem)
lst[-1,2:4]     # array([8, 9])                      

array([8, 9])

In [83]:
lst = np.array([1,2,3,4,5])
np.amin(lst)       # 1
np.amax(lst)       # 5
np.mean(lst)       # 3
np.median(lst)     # 3
np.ptp(lst)        # 4        Range = max value – min value. np.ptp(arr, axis = 0) -> in 2d
np.std(lst)        # 1.5811388300841898     standed deviation
np.var(lst)        # 2.0                    variance   var = mean(abs(x-x.mean())**2)
np.average(lst)    # 3.0                    average    average = sum(x)/len(x)
# np.percentile()    # 3.0                    percentile  percentile = np.percentile(arr, 50)
np.sort(lst)       # array([1, 2, 3, 4, 5])
np.ndim(lst)       # 1    numbe of 
np.shape(lst)      # (5,)    shape of array
type(lst)     # numpy.ndarray
# lst.data()     # [1 2 3 4 5]
lst.dtype        # int32
print(type(lst))

<class 'numpy.ndarray'>


In [54]:
lst_2d = [[1, 2, 3, 4, 5], 
          [6, 7, 8, 9, 10],
          [11, 12, 13, 14, 15] ]
lst_2d = np.array(lst_2d)
lst_2d.dtype      # dtype('int32')
lst_2d.itemsize   # 4
lst_2d.item       # <function ndarray.item>

<function ndarray.item>

In [60]:
lst_2d = [[1, 2, 3, 4, 5], 
          [6, 7, 8, 9, 10],
          [11, 12, 13, 14, 15] ]
lst_2d = np.array(lst_2d,dtype=np.float64)
lst_2d

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

In [56]:
lst_2d = [[1, 2, 3, 4, 5], 
          [6, 7, 8, 9, 10],
          [11, 12, 13, 14, 15] ]
lst_2d = np.array(lst_2d,dtype=np.complex64)
lst_2d

array([[ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j],
       [ 6.+0.j,  7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j],
       [11.+0.j, 12.+0.j, 13.+0.j, 14.+0.j, 15.+0.j]], dtype=complex64)

In [154]:
lst_2d = [[1, 2, 3, 4, 5], 
          [6, 7, 8, 9, 10],
          [11, 12, 13, 14, 15] ]
lst_2d = np.array(lst_2d)
np.sum(lst_2d)     # 120
np.sum(lst_2d, axis = 0)     # array([16, 17, 18, 19, 20])
np.sum(lst_2d,axis= 1)       # array([15, 40, 65])
np.max(lst_2d)      # 15
np.amax(lst_2d)     # 15
np.max(lst_2d, axis = 1)        # array([ 5, 10, 15])
np.amax(lst_2d, axis = 1)       # array([ 5, 10, 15])
np.argmax(lst_2d, axis = 1)     # array([0, 1, 2, 3, 4])
np.mean(lst_2d)    # 8.0
np.median(lst_2d)  # 8.0
np.std(lst_2d)     # 4.320493798938574
np.var(lst_2d)     # 18.666666666666668
np.percentile(lst_2d, 50) # 8.0
np.reshape(lst_2d, (5, 3))
np.ptp(lst_2d)     # 14
np.reshape(lst_2d, (-1))      # array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [133]:
values = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
frequences = np.array([3, 4, 2, 3, 2, 1, 1, 1, 1, 1, 1])  
np.average(values,weights=frequences) #  4.117647058823529   avg = sum(a * weights) / sum(weights)
lst = np.array([5,6])
np.percentile(lst, 50)

5.5

In [144]:
lt = np.arange(1,13).reshape(3, 4)
lt

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [147]:
a = np.arange(12).reshape(3, 4)
b = np.arange(13,13+12).reshape(3, 4)
np.vstack((a,b))
np.hstack((a,b)) 

array([[ 0,  1,  2,  3, 13, 14, 15, 16],
       [ 4,  5,  6,  7, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 21, 22, 23, 24]])

In [148]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [152]:
from numpy import random
random.randint(0,10,(3,4))
# array([[3, 0, 5, 7],
#        [7, 7, 8, 2],
#        [3, 1, 2, 3]])
random.random((3,4))


array([[0.71553541, 0.31696757, 0.80197429, 0.46283947],
       [0.66809138, 0.47776565, 0.64520044, 0.70261601],
       [0.36302321, 0.31651717, 0.65130959, 0.41251358]])

In [117]:
help(np.percentile)

Help on function percentile in module numpy:

percentile(a, q, axis=None, out=None, overwrite_input=False, method='linear', keepdims=False, *, interpolation=None)
    Compute the q-th percentile of the data along the specified axis.
    
    Returns the q-th percentile(s) of the array elements.
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    q : array_like of float
        Percentile or sequence of percentiles to compute, which must be between
        0 and 100 inclusive.
    axis : {int, tuple of int, None}, optional
        Axis or axes along which the percentiles are computed. The
        default is to compute the percentile(s) along a flattened
        version of the array.
    
        .. versionchanged:: 1.9.0
            A tuple of axes is supported
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expect

In [157]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)
  
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

1
2
3
4
5
6
7
8
b'1'
b'2'
b'3'


In [20]:
# lst[:,1] if it is 2d array complet clomn of index 1